INSERT INTO programs (
  id, title, slug, description, content, image, short_description,
  accent_color, sort_order, is_featured, cover_image, data_json, status
) VALUES
('prog1', 'مفاهيم رياضية', 'sports-concepts', 'برنامج يشرح المصطلحات والمفاهيم الأساسية في الرياضة وكرة القدم بلغة واضحة وعميقة، لبناء قاعدة معرفية تساعد القارئ على فهم الموهبة، التدريب، الإدارة، والتطوير.', 'برنامج يشرح المصطلحات والمفاهيم الأساسية في الرياضة وكرة القدم بلغة واضحة وعميقة، لبناء قاعدة معرفية تساعد القارئ على فهم الموهبة، التدريب، الإدارة، والتطوير.', '', 'شرح المصطلحات والمفاهيم الأساسية في الرياضة وكرة القدم بلغة واضحة وعميقة.', '#c8a86e', 1, 0, '', '{"id":"prog1","slug":"sports-concepts","name_ar":"مفاهيم رياضية","name_en":"Sports Concepts","short_description_ar":"شرح المصطلحات والمفاهيم الأساسية في الرياضة وكرة القدم بلغة واضحة وعميقة.","short_description_en":"Explaining fundamental sports and football concepts in clear, in-depth language.","description_ar":"برنامج يشرح المصطلحات والمفاهيم الأساسية في الرياضة وكرة القدم بلغة واضحة وعميقة، لبناء قاعدة معرفية تساعد القارئ على فهم الموهبة، التدريب، الإدارة، والتطوير.","description_en":"A program explaining fundamental sports and football concepts in clear, in-depth language — building the knowledge base needed to understand talent, coaching, management, and development.","logo_url":"","accent_color":"#c8a86e","sort_order":1,"is_active":true}', 'published'),
('prog2', 'الزاوية الضيقة', 'narrow-angle', 'برنامج تحليلي وتأملي يناقش تفاصيل دقيقة في كرة القدم، ويربطها بالثقافة، البيئة، السلوك، الهوية، وطريقة اللعب.', 'برنامج تحليلي وتأملي يناقش تفاصيل دقيقة في كرة القدم، ويربطها بالثقافة، البيئة، السلوك، الهوية، وطريقة اللعب.', '', 'تحليل تفاصيل دقيقة في كرة القدم وربطها بالثقافة والهوية وطريقة اللعب.', '#8b9eb0', 2, 0, '', '{"id":"prog2","slug":"narrow-angle","name_ar":"الزاوية الضيقة","name_en":"The Narrow Angle","short_description_ar":"تحليل تفاصيل دقيقة في كرة القدم وربطها بالثقافة والهوية وطريقة اللعب.","short_description_en":"Analyzing fine details in football and linking them to culture, identity, and playing style.","description_ar":"برنامج تحليلي وتأملي يناقش تفاصيل دقيقة في كرة القدم، ويربطها بالثقافة، البيئة، السلوك، الهوية، وطريقة اللعب.","description_en":"An analytical and reflective program discussing fine details in football and linking them to culture, environment, behavior, identity, and style of play.","logo_url":"","accent_color":"#8b9eb0","sort_order":2,"is_active":true}', 'published'),
('prog3', 'مختبر الموهبة', 'talentlab', 'برنامج علمي يستعرض الأبحاث والدراسات والتجارب الحديثة المرتبطة باكتشاف المواهب وتطويرها، ويحوّل نتائجها إلى فهم عملي للمدرب، اللاعب، الكشاف، الأكاديمية، وولي الأمر.', 'برنامج علمي يستعرض الأبحاث والدراسات والتجارب الحديثة المرتبطة باكتشاف المواهب وتطويرها، ويحوّل نتائجها إلى فهم عملي للمدرب، اللاعب، الكشاف، الأكاديمية، وولي الأمر.', '', 'أبحاث ودراسات حديثة في اكتشاف المواهب تتحول إلى فهم عملي.', '#5a9e7a', 3, 0, '', '{"id":"prog3","slug":"talentlab","name_ar":"مختبر الموهبة","name_en":"TalentLab","short_description_ar":"أبحاث ودراسات حديثة في اكتشاف المواهب تتحول إلى فهم عملي.","short_description_en":"Modern talent research and studies transformed into practical understanding.","description_ar":"برنامج علمي يستعرض الأبحاث والدراسات والتجارب الحديثة المرتبطة باكتشاف المواهب وتطويرها، ويحوّل نتائجها إلى فهم عملي للمدرب، اللاعب، الكشاف، الأكاديمية، وولي الأمر.","description_en":"A scientific program reviewing modern research, studies, and experiments related to talent identification and development — transforming findings into practical understanding for coaches, players, scouts, academies, and parents.","logo_url":"","accent_color":"#5a9e7a","sort_order":3,"is_active":true}', 'published'),
('prog4', 'نماذج تحت المجهر', 'models-under-microscope', 'برنامج يحلل النماذج والأفكار التي طُبقت في كرة القدم وتطوير المواهب، مثل TIPS في أياكس، Bio-Banding، نماذج الأكاديميات، وبرامج الاتحادات.', 'برنامج يحلل النماذج والأفكار التي طُبقت في كرة القدم وتطوير المواهب، مثل TIPS في أياكس، Bio-Banding، نماذج الأكاديميات، وبرامج الاتحادات.', '', 'تحليل النماذج والأفكار التي طُبقت في كرة القدم وتطوير المواهب.', '#9b7ec8', 4, 0, '', '{"id":"prog4","slug":"models-under-microscope","name_ar":"نماذج تحت المجهر","name_en":"Models Under the Microscope","short_description_ar":"تحليل النماذج والأفكار التي طُبقت في كرة القدم وتطوير المواهب.","short_description_en":"Analyzing models and ideas applied in football and talent development.","description_ar":"برنامج يحلل النماذج والأفكار التي طُبقت في كرة القدم وتطوير المواهب، مثل TIPS في أياكس، Bio-Banding، نماذج الأكاديميات، وبرامج الاتحادات.","description_en":"A program analyzing models and ideas applied in football and talent development — including TIPS at Ajax, Bio-Banding, academy models, and federation programs.","logo_url":"","accent_color":"#9b7ec8","sort_order":4,"is_active":true}', 'published'),
('prog5', 'يُحكى أن', 'stories-behind-talent', 'برنامج قصصي وسردي يعرض حكايات وتجارب من عالم كرة القدم: لاعب، كشاف، مدرب، أكاديمية، قرار، أو لحظة غيّرت المسار، بهدف استخراج المعنى خلف القصة.', 'برنامج قصصي وسردي يعرض حكايات وتجارب من عالم كرة القدم: لاعب، كشاف، مدرب، أكاديمية، قرار، أو لحظة غيّرت المسار، بهدف استخراج المعنى خلف القصة.', '', 'حكايات وتجارب من عالم كرة القدم تستخرج المعنى خلف القصة.', '#c87e5a', 5, 0, '', '{"id":"prog5","slug":"stories-behind-talent","name_ar":"يُحكى أن","name_en":"Stories Behind Talent","short_description_ar":"حكايات وتجارب من عالم كرة القدم تستخرج المعنى خلف القصة.","short_description_en":"Stories and experiences from the football world that extract meaning behind the narrative.","description_ar":"برنامج قصصي وسردي يعرض حكايات وتجارب من عالم كرة القدم: لاعب، كشاف، مدرب، أكاديمية، قرار، أو لحظة غيّرت المسار، بهدف استخراج المعنى خلف القصة.","description_en":"A narrative program presenting stories and experiences from the football world — a player, scout, coach, academy, decision, or moment that changed a course — aiming to extract meaning behind the story.","logo_url":"","accent_color":"#c87e5a","sort_order":5,"is_active":true}', 'published'),
('prog6', 'عين الكشاف', 'scouts-eye', 'برنامج عملي يشرح كيف يرى الكشاف اللاعب، وكيف تتحول المشاهدة العادية إلى ملاحظة منظمة وقراءة أعمق للأداء والموهبة.', 'برنامج عملي يشرح كيف يرى الكشاف اللاعب، وكيف تتحول المشاهدة العادية إلى ملاحظة منظمة وقراءة أعمق للأداء والموهبة.', '', 'كيف يرى الكشاف اللاعب وتتحول المشاهدة إلى ملاحظة منظمة.', '#5a7ec8', 6, 0, '', '{"id":"prog6","slug":"scouts-eye","name_ar":"عين الكشاف","name_en":"Scout''s Eye","short_description_ar":"كيف يرى الكشاف اللاعب وتتحول المشاهدة إلى ملاحظة منظمة.","short_description_en":"How the scout sees the player and how observation becomes organized reading.","description_ar":"برنامج عملي يشرح كيف يرى الكشاف اللاعب، وكيف تتحول المشاهدة العادية إلى ملاحظة منظمة وقراءة أعمق للأداء والموهبة.","description_en":"A practical program explaining how the scout sees the player, and how ordinary watching transforms into organized observation and deeper reading of performance and talent.","logo_url":"","accent_color":"#5a7ec8","sort_order":6,"is_active":true}', 'published'),
('prog7', 'خلف الأرقام', 'behind-the-numbers', 'برنامج يشرح البيانات والإحصائيات الرياضية بطريقة مبسطة وناقدة، مثل xG، بيانات GPS، السرعة، المسافات، ومؤشرات الأداء، مع توضيح حدود الأرقام.', 'برنامج يشرح البيانات والإحصائيات الرياضية بطريقة مبسطة وناقدة، مثل xG، بيانات GPS، السرعة، المسافات، ومؤشرات الأداء، مع توضيح حدود الأرقام.', '', 'شرح البيانات والإحصائيات الرياضية بطريقة مبسطة وناقدة.', '#e8b84b', 7, 0, '', '{"id":"prog7","slug":"behind-the-numbers","name_ar":"خلف الأرقام","name_en":"Behind the Numbers","short_description_ar":"شرح البيانات والإحصائيات الرياضية بطريقة مبسطة وناقدة.","short_description_en":"Explaining sports data and statistics in a simplified and critical way.","description_ar":"برنامج يشرح البيانات والإحصائيات الرياضية بطريقة مبسطة وناقدة، مثل xG، بيانات GPS، السرعة، المسافات، ومؤشرات الأداء، مع توضيح حدود الأرقام.","description_en":"A program explaining sports data and statistics in a simplified and critical way — including xG, GPS data, speed, distances, and performance indicators — while clarifying the limits of numbers.","logo_url":"","accent_color":"#e8b84b","sort_order":7,"is_active":true}', 'published'),
('prog8', 'غرفة القرار', 'decision-room', 'برنامج يناقش ما يحدث خلف الملعب: بناء الفريق، إدارة المواهب، قرارات التعاقد، تصعيد اللاعبين، أدوار المدير الرياضي، واستراتيجيات الأندية.', 'برنامج يناقش ما يحدث خلف الملعب: بناء الفريق، إدارة المواهب، قرارات التعاقد، تصعيد اللاعبين، أدوار المدير الرياضي، واستراتيجيات الأندية.', '', 'ما يحدث خلف الملعب: بناء الفريق، إدارة المواهب، واستراتيجيات الأندية.', '#c85a5a', 8, 0, '', '{"id":"prog8","slug":"decision-room","name_ar":"غرفة القرار","name_en":"Decision Room","short_description_ar":"ما يحدث خلف الملعب: بناء الفريق، إدارة المواهب، واستراتيجيات الأندية.","short_description_en":"What happens behind the pitch: team building, talent management, and club strategies.","description_ar":"برنامج يناقش ما يحدث خلف الملعب: بناء الفريق، إدارة المواهب، قرارات التعاقد، تصعيد اللاعبين، أدوار المدير الرياضي، واستراتيجيات الأندية.","description_en":"A program discussing what happens behind the pitch: team building, talent management, signing decisions, player promotion, sporting director roles, and club strategies.","logo_url":"","accent_color":"#c85a5a","sort_order":8,"is_active":true}', 'published'),
('prog9', 'مسارات رياضية', 'sports-pathways', 'برنامج متخصص في الوظائف والمسارات المهنية داخل القطاع الرياضي. كل موضوع يشرح وظيفة محددة من حيث أهدافها، مهامها اليومية، المهارات المطلوبة، التخصصات المناسبة، الشهادات أو الرخص المحتملة، وطريق الدخول إليها.', 'برنامج متخصص في الوظائف والمسارات المهنية داخل القطاع الرياضي. كل موضوع يشرح وظيفة محددة من حيث أهدافها، مهامها اليومية، المهارات المطلوبة، التخصصات المناسبة، الشهادات أو الرخص المحتملة، وطريق الدخول إليها.', '', 'الوظائف والمسارات المهنية داخل القطاع الرياضي.', '#5ac8b0', 9, 0, '', '{"id":"prog9","slug":"sports-pathways","name_ar":"مسارات رياضية","name_en":"Sports Pathways","short_description_ar":"الوظائف والمسارات المهنية داخل القطاع الرياضي.","short_description_en":"Jobs and career pathways within the sports sector.","description_ar":"برنامج متخصص في الوظائف والمسارات المهنية داخل القطاع الرياضي. كل موضوع يشرح وظيفة محددة من حيث أهدافها، مهامها اليومية، المهارات المطلوبة، التخصصات المناسبة، الشهادات أو الرخص المحتملة، وطريق الدخول إليها.","description_en":"A program specializing in jobs and career pathways within the sports sector. Each topic explains a specific role: its goals, daily tasks, required skills, suitable specializations, potential certificates or licenses, and how to enter the field.","logo_url":"","accent_color":"#5ac8b0","sort_order":9,"is_active":true}', 'published'),
('prog10', 'النسخة الأفضل', 'best-version', 'برنامج يركز على تطوير اللاعب من جميع الجوانب: مهاريًا، بدنيًا، تكتيكيًا، ذهنيًا، نفسيًا، اجتماعيًا، وسلوكيًا، بهدف الاقتراب من أفضل نسخة ممكنة داخل الملعب وخارجه.', 'برنامج يركز على تطوير اللاعب من جميع الجوانب: مهاريًا، بدنيًا، تكتيكيًا، ذهنيًا، نفسيًا، اجتماعيًا، وسلوكيًا، بهدف الاقتراب من أفضل نسخة ممكنة داخل الملعب وخارجه.', '', 'تطوير اللاعب من جميع الجوانب للاقتراب من أفضل نسخة ممكنة.', '#7ec85a', 10, 0, '', '{"id":"prog10","slug":"best-version","name_ar":"النسخة الأفضل","name_en":"The Best Version","short_description_ar":"تطوير اللاعب من جميع الجوانب للاقتراب من أفضل نسخة ممكنة.","short_description_en":"Developing the player from all angles to approach the best possible version.","description_ar":"برنامج يركز على تطوير اللاعب من جميع الجوانب: مهاريًا، بدنيًا، تكتيكيًا، ذهنيًا، نفسيًا، اجتماعيًا، وسلوكيًا، بهدف الاقتراب من أفضل نسخة ممكنة داخل الملعب وخارجه.","description_en":"A program focusing on developing the player from all angles: skill, physical, tactical, mental, psychological, social, and behavioral — aiming to approach the best possible version on and off the pitch.","logo_url":"","accent_color":"#7ec85a","sort_order":10,"is_active":true}', 'published')
ON DUPLICATE KEY UPDATE
  title = VALUES(title),
  slug = VALUES(slug),
  description = VALUES(description),
  content = VALUES(content),
  image = VALUES(image),
  short_description = VALUES(short_description),
  accent_color = VALUES(accent_color),
  sort_order = VALUES(sort_order),
  is_featured = VALUES(is_featured),
  cover_image = VALUES(cover_image),
  data_json = VALUES(data_json),
  status = VALUES(status);
